debug: false
server:
  address: 127.0.0.1
  port: 9001
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
# ===============================
# = Log To File Config
# ===============================
logging:
  path: logs/hello
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  file:
    max-size: 5MB
    max-history: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  # ==== zipkin 链路监控，需要时放开注释
  zipkin:
    #    base-url: http://localhost:9411/
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        log_output:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: test-log
          group: log-server-group
          content-type: application/json
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}(${eureka.instance.ip-address}:${server.port}):v${info.version}:${spring.profiles.active}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
    resource:
      token-info-uri: http://server-oauth2/oauth/check_token
# ===============================
# = Ribbon Config
# ===============================
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
ribbon:
  ServerListRefreshInterval: 5000
acp:
  cloud:
    log-server:
      enabled: true