debug: false
server:
  port: 8770
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Ribbon Config
# ===============================
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  eager-load:
    enabled: true
    clients: server-oauth2,atomic-helloworld
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  cloud:
# ===============================
# = GateWay Config
# ===============================
    gateway:
      routes:
      - id: server-oauth2
        uri: lb://server-oauth2
        predicates:
        - Path=/oauth/2.0/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: commonHystrix
            fallbackUri: forward:/hystrixhandle
      - id: atomic-helloworld
        uri: lb://atomic-helloworld
        predicates:
        - Path=/api/helloworld/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: commonHystrix
            fallbackUri: forward:/hystrixhandle
      - id: atomic-hello
        uri: lb://atomic-hello
        predicates:
        - Path=/api/hello/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: commonHystrix
            fallbackUri: forward:/hystrixhandle