debug: false
server:
  port: 9003
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# ===============================
# = Spring Config
# ===============================
spring:
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  # ==== zipkin 链路监控，需要时放开注释
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        log_output:
          binder: kafka
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          # topic
          destination: test-log
          group: log-server-group
          content-type: application/json
# ===============================
# = Eureka Config
# ===============================
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
# ===============================
# = Security Config
# ===============================
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
    resource:
      token-info-uri: http://127.0.0.1:8770/oauth/2.0/oauth/check_token
# ===============================
# = Ribbon Config
# ===============================
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
ribbon:
  ServerListRefreshInterval: 5000
  # 开启懒加载后，如果使用随机端口，注册到 eureka 的端口号永远都是 0，必须使用固定端口号才行
  eager-load:
    enabled: true
    clients: atomic-hello,atomic-world